# Generated by Django 5.2.8 on 2025-11-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('photo_url', models.URLField()),
                ('basic_info', models.JSONField(default=dict)),
                ('asset_declaration', models.JSONField(default=dict)),
                ('government_plan', models.JSONField(default=dict)),
                ('academic_formation', models.JSONField(default=dict)),
                ('career_history', models.JSONField(default=dict)),
                ('background_report', models.JSONField(default=dict)),
                ('current_events', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationDetail',
            fields=[
                ('document_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('case_title', models.CharField(max_length=500)),
                ('case_entity', models.CharField(max_length=255)),
                ('case_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=255)),
                ('timeline', models.JSONField(default=list)),
                ('official_documents', models.JSONField(default=list)),
                ('involved_parties', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('document_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('related_candidate_name', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('image_url', models.URLField()),
                ('source_url', models.URLField()),
            ],
        ),
    ]
